//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplomAPP.entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bolnicaDBEntities : DbContext
    {
        private static bolnicaDBEntities _context;
        public static bolnicaDBEntities GetContext()
        {
            if (_context == null)
                _context = new bolnicaDBEntities();
            return _context;
        }

        public bolnicaDBEntities()
            : base("name=bolnicaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<loginpass> loginpass { get; set; }
        public virtual DbSet<loginpass1> loginpass1 { get; set; }
        public virtual DbSet<priem> priem { get; set; }
        public virtual DbSet<sotrudniki> sotrudniki { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<uslugi> uslugi { get; set; }
    }
}
