//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplomAPP.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class priem
    {
        public int id_priem { get; set; }
        public string fio { get; set; }
        public string polis { get; set; }
        public string pasport { get; set; }
        public string Name_uslugi { get; set; }
        public Nullable<int> id_usluga { get; set; }
        public Nullable<int> id_sot { get; set; }
    
        public virtual sotrudniki sotrudniki { get; set; }
        public virtual uslugi uslugi { get; set; }
    }
}
